services:
  mysql:
    image: mysql:8.0
    container_name: magento-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-magento}
      MYSQL_USER: ${MYSQL_USER:-magento}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-magento}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - magento-net
  nginx:
    image: nginx:mainline-perl
    container_name: magento-nginx
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/module-enabled:/etc/nginx/module-enabled
      - ../instance/store/magento:/var/www/store
    networks:
      - magento-net
  redis:
    image: redis:6.2-alpine
    container_name: magento-redis
    restart: unless-stopped
    networks:
      - magento-net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: magento-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - magento-net
  rabbitmq:
    image: rabbitmq:3-management
    container_name: magento-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672" # Interface web de administração
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASSWORD}
    networks:
      - magento-net
  varnish:
    image: varnish:7.3
    container_name: magento-varnish
    restart: unless-stopped
    ports:
    - '80:80'
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    command: >
      varnishd -F
               -f /etc/varnish/default.vcl
               -s malloc,256m
               -a :80
    depends_on:
      - nginx
    networks:
      - magento-net
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx-proxy/data:/data
      - ./nginx-proxy/letsencrypt:/etc/letsencrypt
    container_name: magento-nginx-proxy
    environment:
      INITIAL_ADMIN_EMAIL: ${NGINX_PROXY_ADMIN_USER_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${NGINX_PROXY_MANAGER_ADMIN_PASSWORD}
      DISABLE_IPV6: 'true'
    networks:
      - magento-net
  store:
    build:
      context: ./php-fpm
    container_name: magento-store
    restart: unless-stopped
    volumes:
      - ../instance/store/magento:/var/www/store
      - ./php-fpm/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www/store
    networks:
      - magento-net

networks:
  magento-net:
    driver: bridge